[connections.snowflak]
account = "XMBEZAI-LLB73013"
user = "CLEHNER"
password = "UpskillHV2025!"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
